logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: INFO
    com.mithrilvault.api: DEBUG

management:
  endpoint:
    health:
      show-details: always
