spring:
  mongodb:
      connection-pool:
        min-size: 20
        max-size: 200
        max-wait-time: 3000ms
        max-connection-life-time: 1h
        max-connection-idle-time: 15m

logging:
  level:
    root: WARN
    org.springframework.web: WARN
    org.springframework.data.mongodb: WARN
    org.mongodb.driver: WARN
    com.mithrilvault.api: INFO

management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: health

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  http2:
    enabled: true

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

spring:
  cloud:
    aws:
      region:
        static: us-east-1
